site_name: 'Aragon Wiki'
site_url: https://wiki.aragon.one
repo_name: 'aragon/aragon-wiki'
repo_url: 'https://github.com/aragon/aragon-wiki'
site_description: 'Wiki for the Aragon Project'
theme:     'material'
site_favicon: 'images/favicon.ico'
extra_css:
  - 'stylesheets/extra.css'
extra:
  palette:
    primary: 'blue grey'
    accent:  'cyan'
  logo:    'images/logo.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/aragon'
    - type: 'medium'
      link: 'https://blog.aragon.one/'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/aragonproject/'
    - type: 'twitter'
      link: 'https://twitter.com/AragonProject'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/aragonproject/'
  feature:
    tabs: false
pages:
  - Home: 'index.md'
  - Documentation:
    - AragonOS: 'documentation/AragonOS_document.md'
    - aragon-core:
      - Home:  'documentation/dev/aragon-core_home.md'
      - Apps:
        - Home: 'documentation/dev/apps/index.md'
        - Voting: 'documentation/dev/apps/voting.md'
        - Token Manager: 'documentation/dev/apps/token-manager.md'
        - Group: 'documentation/dev/apps/group.md'
        - Fundraising: 'documentation/dev/apps/fundraising.md'
        - Vault: 'documentation/dev/apps/vault.md'
        - Finance: 'documentation/dev/apps/finance.md'
      - How to contribute: 'documentation/dev/aragon-core_how_to_contribute.md'
    - Governance:
      - Community Governance Model: 'documentation/Community_Governance_Model.md'
    - Multisigs:
      - Overview: 'documentation/multisigs/overview.md'
      - Foundation: 'documentation/multisigs/foundation.md'
      - Community: 'documentation/multisigs/community.md'
    - Development Plan: 'documentation/Development_Plan.md'
    - Aragon Code of Conduct: 'documentation/Code_of_Conduct.md'
  - Design:
    - Brand:
      - Branding Proposal: 'design/Branding_Proposal.pdf'
      - Identity Guidelines: 'design/Identity_Guidelines.pdf'
    - aragon-dapp: 'https://scene.zeplin.io/project/59a827960d4c4cb2274007f5'
  - Meetings:
    - Aragon HQ:
      - HQ 02: 'meetings/hq/02.md'
      - HQ 01: 'meetings/hq/01.md'
    - Community:
      - Community 04: 'meetings/community/04.md'
      - Community 03: 'meetings/community/03.md'
      - Community 02: 'meetings/community/02.md'
      - Community 01: 'meetings/community/01.md'
    - Dev:
      - Dev 02: 'meetings/dev/02.md'
      - Dev 01: 'meetings/dev/01.md'
  - Jobs:
    - Overview: 'jobs/index.md'
    - Openings:
      - Operations/Executive Assistant: 'jobs/openings/exec_assistant.md'
      - EVM/Solidity Engineer: 'jobs/openings/solidity.md'
      - Frontend and web3 Developer: 'jobs/openings/frontend.md'
      - Community Lead: 'jobs/openings/community.md'
      - Product Manager: 'jobs/openings/product_manager.md'
      - Design Lead: 'jobs/openings/design.md'
  - Blog posts:
    - 2017: 'blog/2017.md'
  - Videos:
    - Tutorials: 'videos/tutorials.md'
    - Meetings:
      - HQ: 'videos/hq.md'
      - Community: 'videos/community.md'
      - Dev: 'videos/dev.md'
    - Interviews: 'videos/interviews.md'
