site_name: 'Aragon Wiki'
site_url: https://wiki.aragon.one
repo_name: 'aragon/aragon-wiki'
repo_url: 'https://github.com/aragon/aragon-wiki'
site_description: 'Wiki for the Aragon Project'
theme:     'material'
site_favicon: 'images/favicon.ico'
extra_css:
  - 'stylesheets/extra.css'
extra:
  palette:
    primary: 'blue grey'
    accent:  'cyan'
  logo:    'images/logo.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/aragon'
    - type: 'twitter'
      link: 'https://twitter.com/AragonProject'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/aragonproject/'
  feature:
    tabs: false
pages:
  - Home: 'index.md'
  - Documentation:
    - Aragon Code of Conduct: 'documentation/Code_of_Conduct.md'
    - Development Plan: 'documentation/Development_Plan.md'
    - For Developers:
      - aragon-core:
        - Home:  'documentation/dev/aragon-core_home.md'
        - DAO Storage: 'documentation/dev/aragon-core_dao_storage.md'
        - How to contribute: 'documentation/dev/aragon-core_how_to_contribute.md'
        - Kernel: 'documentation/dev/aragon-core_kernel.md'
    - Governance:
      - Community Governance Model: 'documentation/Community_Governance_Model.md'
    - Multisigs:
      - Overview: 'documentation/multisigs/overview.md'
      - Foundation: 'documentation/multisigs/foundation.md'
      - Community: 'documentation/multisigs/community.md'
  - Meetings:
    - Aragon HQ:
      - HQ 01: 'meetings/hq/01.md'
    - Community:
      - Community 03: 'meetings/community/03.md'
      - Community 02: 'meetings/community/02.md'
      - Community 01: 'meetings/community/01.md'
    - Dev:
      - Dev 02: 'meetings/dev/02.md'
      - Dev 01: 'meetings/dev/01.md'
  - Jobs:
    - Overview: 'jobs/index.md'
    - Openings:
      - Operations/Executive Assistant: 'jobs/openings/exec_assistant.md'
      - EVM/Solidity Engineer: 'jobs/openings/solidity.md'
      - Frontend and web3 Developer: 'jobs/openings/frontend.md'
      - Community Lead: 'jobs/openings/community.md'
      - Product Manager: 'jobs/openings/product_manager.md'
  - Blog posts:
    - 2017: 'blog/2017.md'
  - Videos:
    - Tutorials: 'videos/tutorials.md'
    - Meetings:
      - HQ: 'videos/hq.md'
      - Community: 'videos/community.md'
      - Dev: 'videos/dev.md'
    - Interviews: 'videos/interviews.md'
